set(chip $ENV{CHIP_ARCH})

if(${chip} STREQUAL "bm1684x" OR ${chip} STREQUAL "bm1688" OR ${chip} STREQUAL "cv186x")
    set(arch "arm64")
elseif(${chip} STREQUAL "cv184x")
    set(arch ${TOOLCHAIN_ARCH})
elseif(${chip} STREQUAL "x86" OR ${chip} STREQUAL "x86_64")
    set(arch "x86_64")
else()
    set(arch "x86_64")
endif()

set(toolchain_path1 "${CMAKE_SOURCE_DIR}/../bm_prebuilt_toolchains")
set(toolchain_path2 "${CMAKE_SOURCE_DIR}/../host-tools")
if(NOT EXISTS ${toolchain_path1})
    set(toolchain_path1 "${CMAKE_SOURCE_DIR}/../../bm_prebuilt_toolchains")
endif()
if(NOT EXISTS ${toolchain_path2})
    set(${toolchain_path2} "${CMAKE_SOURCE_DIR}/../../host-tools")
endif()

if(${arch} STREQUAL "arm64")
    set(CMAKE_C_COMPILER ${toolchain_path1}/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc)
    set(CMAKE_CXX_COMPILER ${toolchain_path1}/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-g++)
elseif(${arch} STREQUAL "musl_arm64")
    set(CMAKE_C_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-musl/bin/aarch64-none-linux-musl-gcc)
    set(CMAKE_CXX_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-musl/bin/aarch64-none-linux-musl-g++)
elseif(${arch} STREQUAL "musl_arm")
    set(CMAKE_C_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-musleabihf/bin/arm-none-linux-musleabihf-gcc)
    set(CMAKE_CXX_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-musleabihf/bin/arm-none-linux-musleabihf-g++)
elseif(${arch} STREQUAL "glibc_arm64")
    set(CMAKE_C_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc)
    set(CMAKE_CXX_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-g++)
elseif(${arch} STREQUAL "glibc_arm")
    set(CMAKE_C_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc)
    set(CMAKE_CXX_COMPILER ${toolchain_path2}/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++)
endif()
