SYSTEM_ID?=0 
CHANNEL_ID?=0 
ENABLE_MMU?=0 
REMAP_MMU?=0 
MULTI_CHAN?=0 
MMU_PAGE?=0

VPU_VPU_WMMU_DEFINES :=

# defined system and channel
VPU_WMMU_DEFINES += -DVIDEO_SYSTEM${SYSTEM_ID}
VPU_WMMU_DEFINES += -DVIDEO_CHANNEL${CHANNEL_ID}

# -DVIDEO_MMU -DVIDEO_MMU_RAND_PTE -DVIDEO_MMU_REMAP -DVIDEO_MULT_CHAN
ifeq ($(ENABLE_MMU), 1)
VPU_WMMU_DEFINES += -DVIDEO_MMU

ifeq ($(REMAP_MMU), 1)
VPU_WMMU_DEFINES += -DVIDEO_MMU_REMAP
endif # REMAP_MMU

ifeq ($(MULTI_CHAN), 1)
VPU_WMMU_DEFINES += -DVIDEO_MULT_CHAN
else
#VPU_WMMU_DEFINES += -DVIDEO_MMU_RAND_PTE
endif # MULTI_CHAN

endif # ENABLE_MMU

ifeq ($(MMU_PAGE), 0) 
VPU_WMMU_DEFINES += -DVIDEO_MMU_PAGE_4K
else ifeq ($(MMU_PAGE), 1)
VPU_WMMU_DEFINES += -DVIDEO_MMU_PAGE_32K
else ifeq ($(MMU_PAGE), 2)
VPU_WMMU_DEFINES += -DVIDEO_MMU_PAGE_64K
else ifeq ($(MMU_PAGE), 3)
VPU_WMMU_DEFINES += -DVIDEO_MMU_PAGE_128K
else
$(error MUST DEFINED VPU MMU PAGE SIZE: 0(4K), 1(32K), 2(64K), 3(128K))
endif # MMU_PAGE
