# Chip 2: pcie2 -> chip3.pcie0 (下行, cdma1), pcie0 -> chip1.pcie2 (上行, cdma0)
[system_if]
slot_id   = 0
socket_id = 2

# 上行: chip2 -> chip1
[pcie_0]
enable         = yes
data_link_type = c2c
send_port      = 0
recv_port      = 0
peer_socketid  = 1
peer_pcieid    = 2

[pcie_1]
enable         = no
data_link_type = pcie

# 下行: chip2 -> chip3
[pcie_2]
enable         = yes
data_link_type = c2c
send_port      = 1
recv_port      = 1
peer_socketid  = 3
peer_pcieid    = 0

[pcie_3]
enable         = no
data_link_type = pcie