# Chip 3: pcie0 -> chip2.pcie2 (上行, cdma0)
[system_if]
slot_id   = 0
socket_id = 3

# 上行: chip3 -> chip2
[pcie_0]
enable         = yes
data_link_type = c2c
send_port      = 0
recv_port      = 0
peer_socketid  = 2
peer_pcieid    = 2

[pcie_1]
enable         = no
data_link_type = pcie

[pcie_2]
enable         = no
data_link_type = pcie

[pcie_3]
enable         = no
data_link_type = pcie