# Chip 0: pcie2 -> chip1.pcie0 (下行, cdma1)
[system_if]
slot_id   = 0
socket_id = 0

# pcie_0 -> chip3.pcie2 (上行, cdma0) — declared by chip3
[pcie_0]
enable         = no
data_link_type = pcie

[pcie_1]
enable         = no
data_link_type = pcie

# 下行: chip0 -> chip1
[pcie_2]
enable         = yes
data_link_type = c2c
send_port      = 1
recv_port      = 1
peer_socketid  = 1
peer_pcieid    = 0

[pcie_3]
enable         = no
data_link_type = pcie