#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define PROJECT_NAME "libsophon"
#define PROJECT_VER "0.4.10"
#define PROJECT_VER_MAJOR 0
#define PROJECT_VER_MINOR 4
#define PROJECT_VER_PATCH 10

#define BUILD_DATE "20241023-115445"

#endif //INCLUDE_GUARD
