set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(GCC_COMPILER_VERSION "" CACHE STRING "GCC Compiler version")
set(GNU_MACHINE "aarch64-linux-gnu" CACHE STRING "GNU compiler triple")
set(CROSS_COMPILE "aarch64-linux-gnu-" CACHE STRING "GNU compiler prefix")
include("${CMAKE_CURRENT_LIST_DIR}/arm.toolchain.cmake")
